version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8081:80"
    volumes:
      - /mnt/storage:/srv
      - /mnt/storage/docker/filebrowser/database:/database
      - /mnt/storage/docker/filebrowser/config:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
